# Generated by Django 2.1 on 2019-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('weekday', models.CharField(max_length=11)),
                ('time', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
                ('classroom', models.IntegerField()),
                ('building', models.IntegerField()),
                ('professor', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
