# Generated by Django 2.1 on 2019-02-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='group_id',
        ),
    ]
