# Generated by Django 2.1 on 2019-02-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='kind',
            new_name='type',
        ),
    ]
