# Generated by Django 2.1 on 2019-02-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190205_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='building',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(max_length=200),
        ),
    ]
